export class FormData {
    public applicantFirstName: string
    public applicantMiddleName: string
    public applicantLastName: string
    public applicantAddress: string
    public applicantEmail: string
    public applicantPhoneNumber: number
    public businessName: string
    public applicantAccountName: string
    public applicantAccountNumber: number
    public issuingBank: string
    public issuingSwiftCode: string
    public beneficiaryFirstName: string
    public beneficiaryMiddleName: string
    public beneficiaryLastName: string
    public beneficiaryAddress: string
    public beneficiaryEmail: string
    public beneficiaryPhoneNumber: number
    public beneficiaryAccountName: string
    public beneficiaryAccountNumber: number
    public beneficiaryBank: string
    public beneficiarySwiftCode: string
    public beneficiaryCity: string
    public lcType: string
    public subType: string
    public applicableRules: string
    public isExpired: boolean
    public shipmentDate: Date
    public portOfDischarge: string
    public portOfLoading: string
    public shipmentTerms: string
    public partialShipment: string
    public transShipment: string
    public issueDate: Date
    public expiryDate: Date
    public usance: string
    public transferable: boolean
    public negotiationPeriod: string
    public commodityCode: string
    public goodsQuantity: string
    public pricePerUnit: number
    public countyOfOrigin: string
    public chargesBorneBy: string
    public amount: number
    public amountCode: string
    public collateralType: string
    public collateralId: number
    public collateralValue: number
    public guarantorName: string
    public guarantorAddress: string
    public guarantorEmail:string
    public guarantorPhoneNumber: number
    public billOfLading: string
    public numberOfCopies: number
    public signed: boolean
    public documentDescription: string
}
