export interface FormData {
     applicantFirstName: string
     applicantMiddleName: string
     applicantLastName: string
     applicantAddress: string
     applicantEmail: string
     applicantPhoneNumber: number
     businessName: string
     applicantAccountName: string
     applicantAccountNumber: number
     issuingBank: string
     issuingSwiftCode: string
     beneficiaryFirstName: string
     beneficiaryMiddleName: string
     beneficiaryLastName: string
     beneficiaryAddress: string
     beneficiaryEmail: string
     beneficiaryPhoneNumber: number
     beneficiaryAccountName: string
     beneficiaryAccountNumber: number
     beneficiaryBank: string
     beneficiarySwiftCode: string
     beneficiaryCity: string
     lcType: string
     subType: string
     applicableRules: string
     isExpired: boolean
     shipmentDate: Date
     portOfDischarge: string
     portOfLoading: string
     shipmentTerms: string
     partialShipment: string
     transShipment: string
     issueDate: Date
     expiryDate: Date
     usance: string
     transferable: boolean
     negotiationPeriod: string
     commodityCode: string
     goodsQuantity: string
     pricePerUnit: number
     countyOfOrigin: string
     chargesBorneBy: string
     amount: number
     amountCode: string
     collateralType: string
     collateralId: number
     collateralValue: number
     guarantorName: string
     guarantorAddress: string
     guarantorEmail:string
     guarantorPhoneNumber: number
     billOfLading: string
     numberOfCopies: number
     signed: boolean
     documentDescription: string
}
