import { RouteInfo } from "./sidebar.metadata";

export const AdminModule: RouteInfo[] = [
  {
    path: "",
    title: "MENUITEMS.MAIN.TEXT",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [],
  },

  {
    path: "/erp-admin/dashboard",
    title: "Dashboard",
    moduleName: "dashboard",
    iconType: "feather",
    icon: "monitor",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [],
  },

  {
    path: "",
    title: "Admin Sub-Modules",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["All Roles", "Manage Role"],
    submenu: [],
  },

  {
    path: "",
    title: "Roles",
    moduleName: "admins",
    iconType: "feather",
    icon: "grid",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: ["All Roles", "Manage Role"],
    submenu: [
      {
        path: "/erp-admin/admin/all-roles",
        title: "All Roles",
        moduleName: "admin",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["All Roles"],
        submenu: [],
      },
      {
        path: "/erp-admin/admin/manage-role",
        title: "Manage Role",
        moduleName: "admin",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Manage Role"],
        submenu: [],
      },
    ],
  },

  {
    path: "",
    title: "Initiate Requests",
    moduleName: "admin",
    iconType: "feather",
    icon: "grid",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: ["All Requests", "Manage Request"],

    submenu: [
      {
        path: "/erp-admin/admin/all-requests",
        title: "All Requests",
        moduleName: "admin",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["All Requests"],
        submenu: [],
      },
      {
        path: "/erp-admin/admin/manage-request",
        title: "Manage Request",
        moduleName: "admin",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Manage Request"],
        submenu: [],
      },
    ],
  }
]